# Site settings
title: Mekor Habracha
email: your-email@domain.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mekorhabracha.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown

collections:
  audio:
    output: true